### ISSUE TITLE
ValueCountAccumulator outputs wrong result when count is negative

### ISSUE THREAD

**Issue by JingsongLi** [flink-extended/flink-dynamic-storage#4]
**Describe the bug**
When multiple retractions are entered in succession, minor compaction may output a negative count.

`ValueCountAccumulator` should not abs to result.

**Environment :**
 - Flink version :  1.15
 - Dynamic storage version: 0.1

**Comment by tsreaper** [comment]
The expected results in tests are also incorrect. Let me fix this.
